<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Pratheep" failures="3" tests="4" name="Test(failed)" time="5.095" errors="0" timestamp="2024-09-19T22:38:40 IST">
  <testcase classname="com.TestNG.TestNG_timeout" name="ApplicationLogut" time="5.025">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.TestNG.TestNG_timeout.ApplicationLogut() didn&amp;apos;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.TestNG.TestNG_timeout.ApplicationLogut() didn't finish within the time-out 5000
at java.base/java.lang.Thread.sleepNanos0(Native Method)
at java.base/java.lang.Thread.sleepNanos(Thread.java:491)
at java.base/java.lang.Thread.sleep(Thread.java:522)
at com.TestNG.TestNG_timeout.ApplicationLogut(TestNG_timeout.java:33)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- ApplicationLogut -->
  <testcase classname="com.TestNG.TestNG_assertions" name="softAssertion" time="0.014">
    <failure type="java.lang.AssertionError" message="Test Fail expected [109] but found [100]">
      <![CDATA[java.lang.AssertionError: Test Fail expected [109] but found [100]
at com.TestNG.TestNG_assertions.softAssertion(TestNG_assertions.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- softAssertion -->
  <testcase classname="com.TestNG.TestNG_dependsOnMethod" name="dependsOnTest" time="0.002">
    <failure type="java.lang.AssertionError" message="Selenium Test expected:&amp;lt;Selenium Test1&amp;gt; but was:&amp;lt;Test Fail&amp;gt;">
      <![CDATA[java.lang.AssertionError: Selenium Test expected:<Selenium Test1> but was:<Test Fail>
at com.TestNG.TestNG_dependsOnMethod.dependsOnTest(TestNG_dependsOnMethod.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- dependsOnTest -->
  <testcase classname="com.TestNG.TestNG_dependsOnMethod" name="Test" time="0.0">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="com.TestNG.TestNG_assertions" name="hardAssertion" time="0.0">
    <ignored/>
  </testcase> <!-- hardAssertion -->
  <testcase classname="com.TestNG.TestNG_timeout" name="Login" time="0.0">
    <ignored/>
  </testcase> <!-- Login -->
  <testcase classname="com.TestNG.TestNG_timeout" name="CloseBrowser" time="0.0">
    <ignored/>
  </testcase> <!-- CloseBrowser -->
  <testcase classname="com.TestNG.TestNG_timeout" name="Browser" time="0.0">
    <ignored/>
  </testcase> <!-- Browser -->
</testsuite> <!-- Test(failed) -->
